// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QueenFlight.Infrastructure.Data;

#nullable disable

namespace QueenFlight.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115130009_LinkUserPreferenceToAirport")]
    partial class LinkUserPreferenceToAirport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QueenFlight.Core.Entities.Aircraft", b =>
                {
                    b.Property<string>("Icao24")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("icao24");

                    b.Property<int?>("AirlineId")
                        .HasColumnType("integer")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastMetadataUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_metadata_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registration_number");

                    b.HasKey("Icao24");

                    b.HasIndex("AirlineId");

                    b.HasIndex("ModelId");

                    b.ToTable("aircrafts");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.AircraftModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IcaoTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icao_type_code");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("WakeTurbulenceCategory")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("wake_turbulence_category");

                    b.HasKey("Id");

                    b.HasIndex("IcaoTypeCode");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("aircraft_models");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CallsignPrefix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("callsign_prefix");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("IataCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iata_code")
                        .IsFixedLength();

                    b.Property<string>("IcaoCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("icao_code");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("IcaoCode")
                        .IsUnique();

                    b.ToTable("airlines");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Airport", b =>
                {
                    b.Property<string>("Ident")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ident");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iata_code");

                    b.Property<string>("IcaoCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao_code");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Ident");

                    b.HasIndex("CountryCode");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.HasIndex("IcaoCode")
                        .IsUnique();

                    b.ToTable("airports");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Country", b =>
                {
                    b.Property<string>("IsoCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.HasKey("IsoCode");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DefaultMapStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("dark")
                        .HasColumnName("default_map_style");

                    b.Property<string>("HomeAirportIata")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("home_airport_iata");

                    b.Property<bool>("ShowWeather")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_weather");

                    b.HasKey("UserId");

                    b.HasIndex("HomeAirportIata");

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Aircraft", b =>
                {
                    b.HasOne("QueenFlight.Core.Entities.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId");

                    b.HasOne("QueenFlight.Core.Entities.AircraftModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.Navigation("Airline");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.AircraftModel", b =>
                {
                    b.HasOne("QueenFlight.Core.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Airline", b =>
                {
                    b.HasOne("QueenFlight.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.Airport", b =>
                {
                    b.HasOne("QueenFlight.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("QueenFlight.Core.Entities.UserPreference", b =>
                {
                    b.HasOne("QueenFlight.Core.Entities.Airport", "HomeAirport")
                        .WithMany()
                        .HasForeignKey("HomeAirportIata")
                        .HasPrincipalKey("IataCode");

                    b.HasOne("QueenFlight.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("QueenFlight.Core.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeAirport");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
